### ISSUE TITLE
Error response from daemon: pull access denied for smartinrub/spring-xmpp-websocket-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by senocak** [smartinrub/spring-xmpp-websocket-reactjs#10]
Error response from daemon: pull access denied for smartinrub/spring-xmpp-websocket-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by smartinrub** [comment]
> Error response from daemon: pull access denied for smartinrub/spring-xmpp-websocket-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
> 
> 

You can build your own image with the Dockerfile and replace it in the docker-compose file

**Comment by smartinrub** [comment]
@senocak I just removed `smartinrub` from the docker image name to avoid confusion. Please, read the `README` file for building the service and running docker-compose. I'm closing this.

**Comment by senocak** [comment]
I think putting `build` section in docker-compose would be much more readable such as;

```
services:
  xmpp-server:
    container_name: spring-xmpp-websocket-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - spring-postgres
      - openfire
```
